### ISSUE TITLE
Add Brazilian timezone, your tests may still fail with only two timezones!

### ISSUE THREAD

**Issue by fer22f** [Jimbly/timezone-mock#9] opened 2017-10-17 14:52 UTC
So, I've been investigating https://github.com/tediousjs/tedious/issues/625 and tried to make a few unit tests to fix the problem, but the problem is oddly specific, and the two timezones provided by your library aren't enough.

The key to the issue is that 00:00:00 doesn't exist on the transition date, when DST gets applied in Brazil. Since the change happens at 02:00:00 in the US, the problem doesn't exist for US timezones.

This has a key impact: Setting the date to the appropriate date while having the clock at 00:00:00 makes the clock jump to 01:00:00 at the same time as changing the date. This causes a few bugs, such as the one I'm investigating.

**Comment by Jimbly** [comment] 2017-10-26 17:37
Hi, I have added the Brazil/East timezone, although it looks like the code you fixed on tedious would also have some failure cases on other DST time zones (though I'm not 100% sure).

Contrary to what you saw in the tedious issue, it seems like when I set my VM's timezone to Brazil/East, putting midnight as a local time on that day sets the Date object to 11PM the previous day (in the previous time zone, which makes sense), not 1AM, and it seems that timezone-mock behaves the same way now, and should let you reproduce the issue.

**Closed by Jimbly** 2017-10-26 17:37 UTC
